/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;


import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author manish
 */
/*
class Jtable{
Jtable(){
    FileHandlingTask fTask = new FileHandlingTask();
    
ArrayList<String> tempNames = new ArrayList<String>();
        ArrayList<String> tempNumbers = new ArrayList<String>();
        fTask.ReadFromFile(tempNames,tempNumbers);
       String coloumns[] = {"Names", "Phone"};
    JFrame frame = new JFrame("Table");
    frame.setSize(300,300);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    String arr[][] = new String[tempNames.size()][2];
    String[] array = tempNames.toArray(new String[0]);
    String[] array2 = tempNumbers.toArray(new String[0]);
   
    for(int x=0;x<tempNames.size();x++){
    arr[x][0]=array[x];
    arr[x][1]=array2[x];
}
    JTable table= new JTable(arr,coloumns);
    JScrollPane jsp = new JScrollPane(table);
    frame.add(jsp); 
    frame.setVisible(true);
}    
}*/

public class Editior extends javax.swing.JFrame {
PhoneBook directory = new PhoneBook();
//StringLinkedList LL= new StringLinkedList();
    /**
     * Creates new form Editior
     */
    public Editior() {
        initComponents();
   //     new Jtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addName = new javax.swing.JTextField();
        addNumber = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        deleteName = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        searchName = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        ListDirectory = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("PHONEBOOK");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Add Contact :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Delete Contact:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Search Contact:");

        addName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addName.setText("Enter Name:");
        addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNameActionPerformed(evt);
            }
        });

        addNumber.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addNumber.setText("Enter Number:");
        addNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNumberActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        deleteName.setText("Enter Name:");

        AddButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        searchName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        searchName.setText("Enter Name:");

        searchButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        ListDirectory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ListDirectory.setText("List");
        ListDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addName, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 465, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ListDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(addName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(addNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ListDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("List Contacts:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel7)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(134, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNameActionPerformed

    private void addNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNumberActionPerformed

    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        int input = JOptionPane.showConfirmDialog(null, "Do you want to delete this contact");
        if(input==0){
            if( directory.DeletePhoneEntry(deleteName.getText())){
                //System.out.println(delete);
                JOptionPane.showMessageDialog(null,"Contact Successfully Deleted!.","Alert",JOptionPane.WARNING_MESSAGE);
                deleteName.setText("");}
            else{
                JOptionPane.showMessageDialog(null,"Contact Not Found!.","Alert",JOptionPane.WARNING_MESSAGE);
                deleteName.setText("");
            }
        }
        else if(input==2){
            JOptionPane.showMessageDialog(null,"Canceled","Alert",JOptionPane.WARNING_MESSAGE);
            deleteName.setText("");

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Are you sure");
        if(input==0){
            directory.AddPhoneEntry(addName.getText(),addNumber.getText());
            JOptionPane.showMessageDialog(null,"Contact Successfully Added.","Alert",JOptionPane.WARNING_MESSAGE);
            addName.setText("");
            addNumber.setText("");
        }
        else if(input==2){
            JOptionPane.showMessageDialog(null,"Canceled","Alert",JOptionPane.WARNING_MESSAGE);
            addName.setText("");
            addNumber.setText("");

        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        ArrayList<String> list = directory.SearchName(searchName.getText());
        System.out.println(list);
        if(list.size()==0){
          JOptionPane.showMessageDialog(null,"Not Found","Alert",JOptionPane.WARNING_MESSAGE);
          searchName.setText("");
          
        }
        else{
ShowSearchTable(list);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void ListDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListDirectoryActionPerformed
        ShowTable();
    }//GEN-LAST:event_ListDirectoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editior().setVisible(true);
            }
        });
    }
    
    
    
//JTable contactsTable ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ListDirectory;
    public javax.swing.JTextField addName;
    public javax.swing.JTextField addNumber;
    private javax.swing.JButton deleteButton;
    public javax.swing.JTextField deleteName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton searchButton;
    public javax.swing.JTextField searchName;
    // End of variables declaration//GEN-END:variables

    
    private class SearchTable extends JFrame{
    JTable contactstable;
    JPanel mainPanel = new JPanel(new BorderLayout());

    private SearchTable(ArrayList<String> list  ){
        this.setLayout(new FlowLayout());
        String [] columns = {"Name" ,"Number"};
        Object[][] contactObj = new Object[list.size()][columns.length];
        for(int i=0 ; i<list.size() ;i++ ){
            for (int j=0; j<columns.length;j++){
                if(j==0)
                    contactObj[i][j]= list.get(i) ;
                if(j==1)
                    contactObj[i][j]=directory.Search(list.get(i));
                
            }
            
            
        }
        contactstable = new JTable(contactObj,columns);
        contactstable.setPreferredScrollableViewportSize(new Dimension(300,300));
        contactstable.setFillsViewportHeight(true);
        contactstable.setRowHeight(25);
        contactstable.setFont(new Font(Font.DIALOG,  Font.BOLD, 13));
        JScrollPane scrollPane = new JScrollPane(contactstable);
        mainPanel.add(scrollPane , BorderLayout.PAGE_START);
        add(mainPanel);
    }

}
public void ShowSearchTable(ArrayList<String> list ){
    
        SearchTable dupTable = new SearchTable(list);
        dupTable.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dupTable.pack();
        dupTable.setLocationByPlatform(true);
        dupTable.setSize(400 , 400);
        dupTable.setVisible(true);
        dupTable.setTitle("Contacts");

    }

    
    
    
private class contactTable extends JFrame{
    JTable contactstable;
    JPanel mainPanel = new JPanel(new BorderLayout());

    private contactTable(){
        this.setLayout(new FlowLayout());
        String [] columns = {"Name" ,"Number"};
        Object[][] contactObj = new Object[directory.getrows()][columns.length];
        for(int i=0 ; i<directory.getrows() ;i++ ){
            for (int j=0; j<columns.length;j++){
                if(j==0)
                    contactObj[i][j]= directory.getRowname(i) ;
                if(j==1)
                    contactObj[i][j]=directory.getRowNumber(i);
                
            }
            
            
        }
        contactstable = new JTable(contactObj,columns);
        contactstable.setPreferredScrollableViewportSize(new Dimension(500,500));
        contactstable.setFillsViewportHeight(true);
        contactstable.setRowHeight(25);
        contactstable.setFont(new Font(Font.DIALOG,  Font.BOLD, 13));
        JScrollPane scrollPane = new JScrollPane(contactstable);
        mainPanel.add(scrollPane , BorderLayout.PAGE_START);
        add(mainPanel);
    }

}
public void ShowTable(){
        contactTable dupTable = new contactTable();
        dupTable.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dupTable.pack();
        dupTable.setLocationByPlatform(true);
        dupTable.setSize(600 , 600);
        dupTable.setVisible(true);
        dupTable.setTitle("Contacts");

    }

}
